apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mqbuepv9t-go
  janus-idp.io/tekton: mqbuepv9t-go
  backstage.io/kubernetes-id: mqbuepv9t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqbuepv9t-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
